version: "3"
services:
  mysql:
    image: mysql:5.6
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - local-net

volumes:
  mysql-data:

    null
networks:
  local-net:
    external: true
